api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: http
  web-secure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "proxy"
  file:
    directory: /etc/traefik

certificatesResolvers:
  myresolver:
    acme:
      email: <email>
      storage: acme.json
      httpChallenge:
        entryPoint: web
