version: "3.8"

secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: "foundry-${INSTANCE_NAME}"
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: /mnt/disk2-p1/foundry-${INSTANCE_NAME}
        target: /data
    ports:
      - target: 30000
        protocol: tcp
    networks:
      - proxy
    environment:
      - FOUNDRY_LICENSE_KEY=${FOUNDRY_LICENSE_KEY}
      - FOUNDRY_WORLD=${DEFAULT_WORLD}
    secrets:
      - source: config_json
        target: config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${INSTANCE_NAME}.rule=Host(`${INSTANCE_NAME}.a-hat.dev`)"
      - "traefik.http.services.${INSTANCE_NAME}.loadbalancer.server.port=30000"

networks:
  proxy:
    external: true
